import { ThemeProvider } from '../components/ThemeProvider';
import RootClientComponent from './RootClientComponent';
import './globals.css';
import { Toaster } from '@components/ui/toaster';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`h-[100dvh] ${inter.className}`}>
      <body className="flex h-full flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <RootClientComponent>{children}</RootClientComponent>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
